### ISSUE TITLE
[Enhancement]似乎并未支持seq,sne,sle,sge,slt,sgt,and,or等指令的高亮与模板

### ISSUE THREAD

**Issue by BobAnkh** [duskmoon314/vscode-mips-mars#2]
下附主要指令表：

![微信图片_20200504200455.png](https://image.bobankh.com/2020/05/04/e9dd24d8fff63.png)

**Comment by duskmoon314** [comment]
Fix in this [commit](https://github.com/duskmoon314/vscode-mips-mars/commit/640ed0c2503f2e8bb406c3b3292c0fcc75b3e493)
